---
##kernel parameters
kernel_parameters:
  - { param: 'net.core.somaxconn', value: '1024' }
  - { param: 'net.core.netdev_max_backlog', value: '5000' }
  - { param: 'net.core.rmem_max', value: '16777216' }
  - { param: 'net.core.wmem_max', value: '16777216' }
  - { param: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216'}
  - { param: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216'}
  - { param: 'net.ipv4.tcp_max_syn_backlog', value: '8096' }
  - { param: 'net.ipv4.tcp_slow_start_after_idle', value: '0' }
  - { param: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { param: 'net.ipv4.ip_local_port_range', value: '10240 65535'}
  - { param: 'net.ipv4.tcp_timestamps', value: '0' }
  - { param: 'vm.swappiness', value: '10' }
  - { param: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
  - { param: 'net.ipv6.conf.default.disable_ipv6', value: '1' }

##set hostname for controle plane
host_name: control-plane01